/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.reingeniera.de.procesos;

import javax.swing.JOptionPane;

/**
 *
 * @author Tisan
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CrearCuentaBtn = new javax.swing.JButton();
        CerrarCuentaBtn = new javax.swing.JButton();
        ModifCuentaBtn = new javax.swing.JButton();
        DepositarBtn = new javax.swing.JButton();
        RetirarBtn = new javax.swing.JButton();
        TransferirBtn = new javax.swing.JButton();
        ConsultCuentasBtn = new javax.swing.JButton();
        BuscarBtn = new javax.swing.JButton();
        HdesactivadasBtn = new javax.swing.JButton();
        HActivasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Bancario");

        CrearCuentaBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        CrearCuentaBtn.setText("Crear cuenta");
        CrearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaBtnActionPerformed(evt);
            }
        });

        CerrarCuentaBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        CerrarCuentaBtn.setText("Cerrar Cuenta");
        CerrarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarCuentaBtnActionPerformed(evt);
            }
        });

        ModifCuentaBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        ModifCuentaBtn.setText("Modificar Cuenta");
        ModifCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifCuentaBtnActionPerformed(evt);
            }
        });

        DepositarBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        DepositarBtn.setText("Depositar");
        DepositarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositarBtnActionPerformed(evt);
            }
        });

        RetirarBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        RetirarBtn.setText("Retirar");
        RetirarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarBtnActionPerformed(evt);
            }
        });

        TransferirBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        TransferirBtn.setText("Transferir");
        TransferirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirBtnActionPerformed(evt);
            }
        });

        ConsultCuentasBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        ConsultCuentasBtn.setText("Consulta cuentas");
        ConsultCuentasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultCuentasBtnActionPerformed(evt);
            }
        });

        BuscarBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar por id");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        HdesactivadasBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        HdesactivadasBtn.setText("H. desactivadas");
        HdesactivadasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HdesactivadasBtnActionPerformed(evt);
            }
        });

        HActivasBtn.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        HActivasBtn.setText("Historial activas");
        HActivasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActivasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DepositarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CerrarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModifCuentaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RetirarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransferirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ConsultCuentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HdesactivadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HActivasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetirarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransferirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HActivasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultCuentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HdesactivadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaBtnActionPerformed
        CrearCuentaFrame frameCrear = new CrearCuentaFrame();
        frameCrear.setVisible(true);
    }//GEN-LAST:event_CrearCuentaBtnActionPerformed

    private void CerrarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarCuentaBtnActionPerformed
        CerrarCuentaFrame frameCerrar = new CerrarCuentaFrame();
        frameCerrar.setVisible(true);
    }//GEN-LAST:event_CerrarCuentaBtnActionPerformed

    private void ModifCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifCuentaBtnActionPerformed
        ModificarCuentaFrame frameModificar = new ModificarCuentaFrame();
        frameModificar.setVisible(true);
    }//GEN-LAST:event_ModifCuentaBtnActionPerformed

    private void DepositarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositarBtnActionPerformed
        DepositarFrame frameDepo = new DepositarFrame();
        frameDepo.setVisible(true);
    }//GEN-LAST:event_DepositarBtnActionPerformed

    private void RetirarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarBtnActionPerformed
        RetirarFrame frameRetiro = new RetirarFrame();
        frameRetiro.setVisible(true);
    }//GEN-LAST:event_RetirarBtnActionPerformed

    private void TransferirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirBtnActionPerformed
        TransferirFrame frameTransf = new TransferirFrame();
        frameTransf.setVisible(true);
    }//GEN-LAST:event_TransferirBtnActionPerformed

    private void ConsultCuentasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultCuentasBtnActionPerformed
        ConsultarCuentasFrame frameConsulta = new ConsultarCuentasFrame();
        frameConsulta.setVisible(true);
    }//GEN-LAST:event_ConsultCuentasBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        BuscarCuentaFrame frameBuscar = new BuscarCuentaFrame();
        frameBuscar.setVisible(true);
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void HdesactivadasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HdesactivadasBtnActionPerformed
        HistorialDesactivadasFrame frameHistCerradas = new HistorialDesactivadasFrame();
        frameHistCerradas.setVisible(true);
    }//GEN-LAST:event_HdesactivadasBtnActionPerformed

    private void HActivasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActivasBtnActionPerformed
        HistorialActivasFrame frameHist = new HistorialActivasFrame();
        frameHist.setVisible(true);
    }//GEN-LAST:event_HActivasBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JButton CerrarCuentaBtn;
    private javax.swing.JButton ConsultCuentasBtn;
    private javax.swing.JButton CrearCuentaBtn;
    private javax.swing.JButton DepositarBtn;
    private javax.swing.JButton HActivasBtn;
    private javax.swing.JButton HdesactivadasBtn;
    private javax.swing.JButton ModifCuentaBtn;
    private javax.swing.JButton RetirarBtn;
    private javax.swing.JButton TransferirBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
