/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.reingeniera.de.procesos;

/**
 *
 * @author ajcd8
 */
import java.io.*;
import java.util.*;
import javax.swing.*;

public class modificarCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modificarCuenta.class.getName());

    /**
     * Creates new form modificarCuenta
     */
    
    
    private Cuenta cuenta;
    
    public modificarCuenta() {
        initComponents();
        String idBuscar = JOptionPane.showInputDialog(null, "Ingrese el ID de la cuenta a modificar:",JOptionPane.QUESTION_MESSAGE);
        if (idBuscar == null || idBuscar.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error.");
            this.dispose();
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            cierreForzado();
            return;
        }

        cuenta = buscarCuenta(idBuscar.trim());

        if (cuenta == null) {
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            dispose();
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(null, "No existe cuenta con ID: " + idBuscar);
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            this.dispose();
            cierreForzado();
            cierreForzado();
            dispose();
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            return;
        }
        cargarDatos();
        setLocationRelativeTo(null);
    }

    private void cargarDatos() {
        id.setText(cuenta.getId());
        viejoUsername.setText(cuenta.getNombreCliente());
        nuevoUsername.setText("");
    }

    private Cuenta buscarCuenta(String id) {
        return GestorCuentas.buscarCuenta(id);
    }

    private void guardarCambios() {
        ArrayList<Cuenta> lista = GestorCuentas.cargarCuentas();
        for (int x = 0; x<lista.size(); x++) {
            if (lista.get(x).getId().equals(cuenta.getId())) {
                lista.get(x).setNombreCliente(cuenta.getNombreCliente());
                break;
            }}
        try {
            GestorCuentas.guardarCuentas(lista);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Err");
        }
    }
    
    private void cierreForzado() { //Unico comentario mio, no queria cerrarse y no se proque, asi que le pedi a chatgpt que me diera esto, espero que funcione bien.
    if (cuenta == null) {
        SwingUtilities.invokeLater(() -> this.dispose());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoUsername = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viejoUsername = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsernameActionPerformed(evt);
            }
        });

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevo nombre:");

        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setText("ID de cuenta:");

        viejoUsername.setEditable(false);
        viejoUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viejoUsernameActionPerformed(evt);
            }
        });

        aceptar.setBackground(new java.awt.Color(102, 255, 102));
        aceptar.setText("Aceptar cambios");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viejoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viejoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoUsernameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void viejoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viejoUsernameActionPerformed
        if(viejoUsername == null){this.dispose();this.dispose();this.dispose();this.dispose();this.dispose();this.dispose();this.dispose(); dispose(); setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);}
    }//GEN-LAST:event_viejoUsernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String nuevo = nuevoUsername.getText().trim();

        if (nuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe un nombre.");
            return;
        }

        if (nuevo.equals(cuenta.getNombreCliente())) {
            JOptionPane.showMessageDialog(this, "El nombre es el mismo al anterior.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,"Seguro de Cambiar el nombre de '" + cuenta.getNombreCliente() +"?","Confirmar",JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            cuenta.setNombreCliente(nuevo);
            guardarCambios();
            JOptionPane.showMessageDialog(this, "Nombre cambiad.");
            this.dispose(); 
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new modificarCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nuevoUsername;
    private javax.swing.JTextField viejoUsername;
    // End of variables declaration//GEN-END:variables
}
